# Generated by Django 4.1.5 on 2023-01-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10)),
                ('nationality', models.CharField(choices=[('BRA', 'Brasileira'), ('PRT', 'Portuguesa')], default='BRA', max_length=10)),
                ('faceImage', models.ImageField(blank=True, upload_to='images', verbose_name='faceImage')),
                ('faceImageBinary', models.BinaryField(null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
